### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fatawasd-dev** [achowba/node-mysql-crud-app#1]
I got the error when add data.

> ``{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\test-node\\crud\\public\\assets\\img\\username.png"}``

**Comment by n1lsan** [comment]
> I got the error when add data.
> 
> > `{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\test-node\\crud\\public\\assets\\img\\username.png"}`

Just create folders:
public/assets/img

And try again
